[features]
seeds = true
skip-lint = false
[programs.localnet]
nft_staking_test = "3pvNETr3Kqf4zTuUmfZUj3QzAHxAXk4icc7F5YsztLar"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
